# Generated by Django 5.1.2 on 2024-12-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_reservation_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
